// stopwatch-tracker-react/src/lib/Stopwatch.tsx
import { useEffect, useState } from "react";
import { store, UiReactWithSchemas } from "./tinybase-store";
import { assumeDefined, msToUnits, unitsToDisplayStrings } from "./utils";
import StopwatchHistoryDisplay from "./StopwatchHistoryDisplay";
const { useCell } = UiReactWithSchemas;



export function Stopwatch(props: { stopwatchId: string }) {
    let title = assumeDefined(useCell("stopwatches", props.stopwatchId, "title"))
    let startTime = assumeDefined(useCell("stopwatches", props.stopwatchId, "startTime"))
    let paused = assumeDefined(useCell("stopwatches", props.stopwatchId, "paused"))
    let pausedTimeCount = assumeDefined(useCell("stopwatches",props.stopwatchId,"pausedTimeCount"))
    let lastPausedTime = assumeDefined(useCell("stopwatches", props.stopwatchId, "lastPausedTime"))

    let currentTime = useCurrentTime(); // causes a refresh every X milliseconds
    
    
    let elapsedTimeMillis = (paused ? lastPausedTime : currentTime) - startTime - pausedTimeCount

        // 


    function onDeleteButtonPressed() {
        const confirmDelete = confirm(`Delete "${title}?"`);
        if (!confirmDelete) return;

        store.delRow("stopwatches", props.stopwatchId);
    }

    
    // if (!stopwatchExists) throw new Error("Stopwatch does not exist");
    return (
        <div className="border-2 bg-neutral-400 dark:bg-[hsl(0,0%,12%)] border-black dark:border-gray-500 rounded-md px-3 py-3 max-w-fit h-fit relative">
            <button
                className="bg-red-600 border-2  text-white   border-black dark:border-neutral-300 rounded-sm  hover:brightness-125 py-0 px-1 font-mono text-sm absolute right-2 top-2"
                onClick={onDeleteButtonPressed}
            >
                X
            </button>

            <h1 className="text-xl decoration-1 font-semibold text-center">
                <div> {title}</div>
                {/* todo: make contenteditale */}
            </h1>

            

            <div className="pt-3"></div>
            {/* <p>time:{currentTime}, startTime:{startTime}</p>
            <p>c-st: {currentTime - startTime}</p>
            <p>pausedTimeCount:{pausedTimeCount}, lastPausedTime:{lastPausedTime}</p> */}

            <TimeDisplay elapsedTimeMillis={elapsedTimeMillis} />

            <div className="pt-3"></div>

            <StopwatchButtons stopwatchId={props.stopwatchId} elapsedTimeMillis={elapsedTimeMillis} />

            <div className="pt-3"></div>

            <StopwatchHistoryDisplay stopwatchId={props.stopwatchId} />
        </div>
    );
}


const REFRESH_RATE = 16; // milliseconds. //potential: can make this into a editable setting
function useCurrentTime(){
    //credit to react docs https://codesandbox.io/p/sandbox/rxhzkx?file=%252Fsrc%252FApp.js%253A14%252C1 for idea to be a hook
    // could make it a context provider so that all components can use the same instance of it.
    
    // const [currentTime, setCurrentTime] = useState(Date.now());
    let currentTime = Date.now();


    const [refreshTriggerer, setRf] = useState(false)
    function triggerRerender(){
        setRf((p)=>!p)
    }
    // need to do it like this instead of w/ useState(date.now) because otherwise cell values (ie startime) may update and cause a rerender before currentTime is updated, and cause the timer to have a flash of incorrect information
    // this way currentTime is automatically fetched on each render, and just forced to rerender every X millis. 
    
    // maybe I could also make this a provider or a singleton or something and have another function like makeCurrentTimeUpToDate(). But i think this works fine
    
    
    
    useEffect(() => {
        const interval = setInterval(
            () =>{
                // setCurrentTime(Date.now())
                // currentTime = Date.now() // not needed
                triggerRerender()
            },
            REFRESH_RATE
        );
        return () => {
            clearInterval(interval);
        };
    }, []);
    
    return currentTime
}



function TimeDisplay(props: { elapsedTimeMillis: number }) {
    let elapsedTimeMillis = props.elapsedTimeMillis;
    let elapsedTimeUnits = msToUnits(elapsedTimeMillis);
    let timeDisplay = unitsToDisplayStrings(elapsedTimeUnits);

    function Colon(props: { className?: string } = { className: "" }) {
        return (
            <span className={`${props.className} font-['Inter_Variable']`}>:</span>
        );
    }

    return (
        // todo tidy/change classNames
        <p className="border-2 border-black dark:border-neutral-300 rounded-md text-5xl px-4 py-1 bg-stone-300 dark:bg-stone-600 w-fit  text-center m-auto font-['Noto_Mono']">
            {elapsedTimeUnits.days > 0 && (
                <span>
                    {timeDisplay.days}
                    <Colon />
                </span>
            )}
            {timeDisplay.hours}
            <Colon className={""} />
            {timeDisplay.minutes}
            <Colon />
            {timeDisplay.seconds}
            <span className="text-base">.</span>
            <span className="text-xs">{timeDisplay.milliseconds}</span>
        </p>
    );
}

function StopwatchButtons(props: {
    stopwatchId: string;
    elapsedTimeMillis: number;
}) {
    const paused = useCell("stopwatches", props.stopwatchId, "paused")!;

    // used in functions, doesnt need to be a hook
    // const lastPausedTime = useCell( "stopwatches",  props.stopwatchId, "lastPausedTime")!;
    // const pausedTimeCount = useCell("stopwatches", props.stopwatchId, "pausedTimeCount")!;
    // const startTime = useCell("stopwatches", props.stopwatchId, "startTime")!;

    

    function pause() {
        const now = Date.now() // should it begetCurrentTime from context?
        store.transaction(() => {
            store.setCell('stopwatches', props.stopwatchId, 'lastPausedTime', now)
            store.setCell('stopwatches', props.stopwatchId, 'paused', true)
        })
    }
    function unpause() {
        const now = Date.now();
        
        store.transaction(() => {
            const lastPausedTime = assumeDefined(store.getCell('stopwatches', props.stopwatchId, 'lastPausedTime'))
            const pausedTimeCount = assumeDefined(store.getCell('stopwatches', props.stopwatchId, 'pausedTimeCount'))
            
            if (lastPausedTime === -1) throw new Error("Timer is not paused");

            const newTime = pausedTimeCount + (now - lastPausedTime);
            store.setCell("stopwatches", props.stopwatchId, "pausedTimeCount", newTime);

            store.setCell("stopwatches", props.stopwatchId, "paused", false);

            store.setCell("stopwatches", props.stopwatchId, "lastPausedTime", -1);
        });

        // currentTime = Date.now();
    }

    function reset() {
        const now = Date.now()

        store.transaction(() => {

            const paused = store.getCell('stopwatches', props.stopwatchId, 'paused') ?? (()=>{throw new Error("Timer is not paused")})()
            const lastPausedTime = store.getCell('stopwatches', props.stopwatchId, 'lastPausedTime')!
            const pausedTimeCount = store.getCell('stopwatches', props.stopwatchId, 'pausedTimeCount')!
            const startTime = store.getCell('stopwatches', props.stopwatchId, 'startTime')!
            



            store.setCell('stopwatches', props.stopwatchId, 'startTime', now)
            store.setCell('stopwatches', props.stopwatchId, 'pausedTimeCount', 0)

            if (paused) {
                store.setCell('stopwatches', props.stopwatchId, 'lastPausedTime', now)
            }
            else {
                store.setCell('stopwatches', props.stopwatchId, 'lastPausedTime', -1)
            }

            // auto pause after reset, still considering whether to keep this
            store.setCell('stopwatches', props.stopwatchId, 'paused', true)
            store.setCell('stopwatches', props.stopwatchId, 'lastPausedTime', now)

            // Save to history
            // should be good but slight chance of some kind of race condition here
            store.addRow('stopwatchHistory', {
                stopwatchId: props.stopwatchId,
                elapsedTimeCount: (paused ? (lastPausedTime! - startTime - pausedTimeCount) : (now - startTime - pausedTimeCount)), // WET with elapsedTimeMillis,
                startTime: startTime,
                endTime: now,
                pausedTimeCount: pausedTimeCount,
            })
            
        })

        // currentTime = Date.now();
    }
    

    const controlButtonCSS = "border-2 border-black dark:border-neutral-300 rounded-md text-white  min-w-24 px-1 py-1 pb-1.5"
    return (
        <div className="flex gap-3 items-center justify-evenly flex-wrap">
            {paused ? (
                (props.elapsedTimeMillis > 0) ? (
                    <button className={`${controlButtonCSS} bg-lime-700`} onClick={unpause}>
                        Resume
                    </button>
                ):
                (
                    <button className={`${controlButtonCSS} bg-lime-700`} onClick={unpause}>
                        Start
                    </button>
                )
            ) : (
                <button className={`${controlButtonCSS} bg-lime-600`} onClick={pause}>
                    Pause
                </button>
            )}


            <button className={`${controlButtonCSS} bg-red-600`} onClick={reset}>
                Reset
            </button>
        </div>
    );
}

// src/lib/Stopwatch.svelte
<!-- Please client render pages with this component -->
<script lang="ts">
	import { browser, building, dev } from "$app/environment";
    import store from "$lib/tinybase"
	import { onMount } from "svelte";
	import StopwatchHistoryDisplay from "./stopwatch-history/StopwatchHistoryDisplay.svelte";
	import { msToUnits, unitsToDisplayString } from "./stopwatch";

    type Milliseconds = number 

    let {
        stopwatchId,
        refreshRate=9
    }: {
        stopwatchId: string,
        refreshRate?: Milliseconds  
    } = $props() // annoying that you are forced to write every prop twice to type it in svelte 5.


    if (!browser && !building) {
        throw new Error("this component can only be rendered in the browser")
    }
    
    //--------DB Data----------
    let startTime = $state(store.getCell('stopwatches', stopwatchId, "startTime")!)
    let paused = $state(store.getCell('stopwatches', stopwatchId, "paused")!)
    let title = $state(store.getCell('stopwatches', stopwatchId, "title")!)
    let lastPausedTime = $state(store.getCell('stopwatches', stopwatchId, "lastPausedTime")!)
    let pausedTimeCount = $state(store.getCell('stopwatches', stopwatchId, "pausedTimeCount")!)
    
    if (
        startTime === undefined || paused === undefined || title === undefined || lastPausedTime === undefined || pausedTimeCount === undefined
    ) {
        console.warn({
            startTime, paused, title, lastPausedTime, pausedTimeCount
        })
        throw new Error('something was undefined in timer data')
    }
    

    $effect(() => {
        
        const startTimeListener = store.addCellListener(
            'stopwatches', stopwatchId, 'startTime',
            (store, tableId, rowId, cellId, newCell, oldCell, getCellChange) => {
                startTime = newCell
            },
        );
        const pausedListener = store.addCellListener(
            'stopwatches', stopwatchId, 'paused',
            (store, tableId, rowId, cellId, newCell, oldCell, getCellChange) => {
                paused = newCell
            },
        );
        const titleListener = store.addCellListener(
            'stopwatches', stopwatchId, 'title',
            (store, tableId, rowId, cellId, newCell, oldCell, getCellChange) => {
                title = newCell
            },
        );
        const lastPausedTimeListener = store.addCellListener(
            'stopwatches', stopwatchId, 'lastPausedTime',
            (store, tableId, rowId, cellId, newCell, oldCell, getCellChange) => {
                lastPausedTime = newCell
            },
        );
        const pausedTimeCountListener = store.addCellListener(
            'stopwatches', stopwatchId, 'pausedTimeCount',
            (store, tableId, rowId, cellId, newCell, oldCell, getCellChange) => {
                pausedTimeCount = newCell
            },
        );

        console.log({
            startTime, paused, title, lastPausedTime, pausedTimeCount})

        return () => {
            store.delListener(startTimeListener)
            store.delListener(pausedListener)
            store.delListener(titleListener)
            store.delListener(lastPausedTimeListener)
            store.delListener(pausedTimeCountListener)
        }

    })
    //binding title to store. not sure if good idea or not
    $effect (() => {
        if (title !== undefined) {
            store.setCell('stopwatches', stopwatchId, 'title', title)
        }
    })
    //------------
    


    let currentTime = $state(Date.now());
    
    let elapsedTimeMillis = $derived(paused ? lastPausedTime! - startTime - pausedTimeCount : currentTime - startTime - pausedTimeCount)


    //first time
    

    $effect(() => {
        if (paused) {
            return
        }

        const interval = setInterval(() => {
            currentTime = Date.now();
            // console.log("u")
        }, refreshRate)

		return () => {
			// if a callback is provided, it will run
			// a) immediately before the effect re-runs
			// b) when the component is destroyed
			clearInterval(interval);
		};
	});

    function pause() {
        const now = Date.now()
        store.transaction(() => {
            store.setCell('stopwatches', stopwatchId, 'lastPausedTime', now)
            store.setCell('stopwatches', stopwatchId, 'paused', true)
        })
    }

    function unpause() {
        const now = Date.now()
        if (lastPausedTime === -1)
            throw new Error('Timer is not paused')


        store.transaction(() => {
            store.setCell('stopwatches', stopwatchId, 'pausedTimeCount', pausedTimeCount + (now - lastPausedTime))

            store.setCell('stopwatches', stopwatchId, 'paused', false)

            store.setCell('stopwatches', stopwatchId, 'lastPausedTime', -1)
        })
        
        currentTime = Date.now();
        
    }

    function reset(){
        const now = Date.now()

        store.transaction(() => {
            store.setCell('stopwatches', stopwatchId, 'startTime', now)
            store.setCell('stopwatches', stopwatchId, 'pausedTimeCount', 0)

            if (paused) {
                store.setCell('stopwatches', stopwatchId, 'lastPausedTime', now)
            }
            else {
                store.setCell('stopwatches', stopwatchId, 'lastPausedTime', -1)
            }

            // auto pause after reset, still considering whether to keep this
            store.setCell('stopwatches', stopwatchId, 'paused', true)
            store.setCell('stopwatches', stopwatchId, 'lastPausedTime', now)

            // Save to history
            // should be good but slight chance of some kind of race condition here
            store.addRow('stopwatchHistory', {
                stopwatchId: stopwatchId,
                elapsedTimeCount: (paused ? (lastPausedTime! - startTime - pausedTimeCount) : (now - startTime - pausedTimeCount)), // WET with elapsedTimeMillis,
                startTime: startTime,
                endTime: now,
                pausedTimeCount: pausedTimeCount,
            })
            
        })

        currentTime = Date.now();
    }

    function deleteButtonPressed(){
        const confirmDelete = confirm(`Delete "${title}?"`)
        if (!confirmDelete) 
            return
        
        store.transaction(() => {
            store.delRow('stopwatches', stopwatchId)
        })
        // const historyIsClear = false
        // if (!historyIsClear) {
        //     const doClear = confirm("Would you like to clear the history of this stopwatch?")
        //     if (doClear){

        //         return
        //     }
        // }
        

        // const doDelete = confirm("Would you like to delete this stopwatch?")
    }



    let elapsedTimeUnits = $derived(msToUnits(elapsedTimeMillis))
    let timeDisplay = $derived(unitsToDisplayString(elapsedTimeUnits))
    


</script>

<div class="border-2 bg-neutral-400 dark:bg-[hsl(0,0%,12%)] border-black dark:border-gray-500 rounded-md px-3 py-3 max-w-fit h-fit relative">
    <h1 class="text-xl text-[1.unitsToDisplayStringnter  decoration-1 font-semibold">
        <div contenteditable="true" bind:innerText={title}>{title} </div>
    </h1>
    <button 
        class="bg-red-600 border-2  text-white   border-black dark:border-neutral-300 rounded-sm  hover:brightness-125 py-0 px-1 font-mono rounded-sm text-sm absolute right-2 top-2"
        onclick={deleteButtonPressed}
    >
        X
    </button>
    
    <div class="pt-3"></div>
    
    <p class = "time">
        <!-- {secondsString} -->
        
        {#if (elapsedTimeUnits.days > 0)}{timeDisplay.days}:{/if}{timeDisplay.hours}:{timeDisplay.minutes}:{timeDisplay.seconds}<span class="text-base">. </span><span class="text-xs">{timeDisplay.milliseconds}</span>
    </p>

    <div class="pt-3"></div>

    <div class="flex gap-3 items-center justify-evenly flex-wrap" >
        {#if paused}
            {#if elapsedTimeMillis > 0}
                <button class="control-button bg-lime-700" onclick={unpause}>
                    Resume
                </button>
            {:else}
                <button class="control-button bg-lime-700" onclick={unpause}>
                    Start
                </button>
            {/if}
        {:else }
            <button class="control-button bg-lime-600" onclick={pause}>Pause</button>
        {/if}

        <button class="control-button bg-red-600"  onclick={reset}>
            Reset
        </button>
    </div>

    <div class="pt-3"></div>

    <!-- Extract -->
    <StopwatchHistoryDisplay stopwatchId={stopwatchId}/>
</div>

<style lang="postcss">
    .time {
        width: fit-content;
        margin:auto; 
        /* background: #64748b; */

        @apply border-2 border-black dark:border-neutral-300 rounded-md text-5xl px-4 py-1 pb-1.5;
        @apply bg-stone-300 dark:bg-stone-600
    }
    .control-button {
        /* border: 2px solid black; */


        @apply border-2 border-black dark:border-neutral-300 rounded-md text-white  min-w-24 px-1 py-1 pb-1.5
    }
</style>
